=begin
#Selling Partner API for Catalog Items

#The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.

OpenAPI spec version: 2020-12-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.26
=end

require 'spec_helper'
require 'json'

# Unit tests for AmzSpApi::CatalogItemsApiModel::CatalogApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CatalogApi' do
  before do
    # run before each test
    @instance = AmzSpApi::CatalogItemsApiModel::CatalogApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CatalogApi' do
    it 'should create an instance of CatalogApi' do
      expect(@instance).to be_instance_of(AmzSpApi::CatalogItemsApiModel::CatalogApi)
    end
  end

  # unit tests for get_catalog_item
  # Retrieves details for an item in the Amazon catalog.  **Usage Plans:**  | Plan type | Rate (requests per second) | Burst | | ---- | ---- | ---- | |Default| 5 | 5 | |Selling partner specific| Variable | Variable |  The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
  # @param asin The Amazon Standard Identification Number (ASIN) of the item.
  # @param marketplace_ids A comma-delimited list of Amazon marketplace identifiers. Data sets in the response contain data only for the specified marketplaces.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :included_data A comma-delimited list of data sets to include in the response. Default: summaries.
  # @option opts [String] :locale Locale for retrieving localized summaries. Defaults to the primary locale of the marketplace.
  # @return [Item]
  describe 'get_catalog_item test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for search_catalog_items
  # Search for and return a list of Amazon catalog items and associated information.  **Usage Plans:**  | Plan type | Rate (requests per second) | Burst | | ---- | ---- | ---- | |Default| 1 | 5 | |Selling partner specific| Variable | Variable |  The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see \&quot;Usage Plans and Rate Limits\&quot; in the Selling Partner API documentation.
  # @param keywords A comma-delimited list of words or item identifiers to search the Amazon catalog for.
  # @param marketplace_ids A comma-delimited list of Amazon marketplace identifiers for the request.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :included_data A comma-delimited list of data sets to include in the response. Default: summaries.
  # @option opts [Array<String>] :brand_names A comma-delimited list of brand names to limit the search to.
  # @option opts [Array<String>] :classification_ids A comma-delimited list of classification identifiers to limit the search to.
  # @option opts [Integer] :page_size Number of results to be returned per page.
  # @option opts [String] :page_token A token to fetch a certain page when there are multiple pages worth of results.
  # @option opts [String] :keywords_locale The language the keywords are provided in. Defaults to the primary locale of the marketplace.
  # @option opts [String] :locale Locale for retrieving localized summaries. Defaults to the primary locale of the marketplace.
  # @return [ItemSearchResults]
  describe 'search_catalog_items test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
